import { NextRequest, NextResponse } from 'next/server'
import path from 'path'
import fs from 'fs'
import { spawn } from 'child_process'

// Check if we should use the real worker or mock converter
const USE_REAL_WORKER = process.env.NODE_ENV === 'development' || process.env.USE_REAL_WORKER === 'true'

// Check if a real uploaded file exists on disk for this project
function getUploadedFilePath(projectId: string): string | null {
  // Check for common file extensions in converter uploads directory
  const uploadsDir = path.join(process.cwd(), 'converter', 'uploads')
  const extensions = ['.docx', '.md', '.rtf']
  
  for (const ext of extensions) {
    const filePath = path.join(uploadsDir, `${projectId}${ext}`)
    if (fs.existsSync(filePath)) {
      console.log(`Found existing file: ${filePath}`)
      return filePath
    }
  }
  
  return null
}

// Mock converter function for demonstration (fallback)
async function mockConvert(projectId: string, templateId: string, userPlan: string = 'free'): Promise<void> {
  // Simulate conversion delay
  await new Promise(resolve => setTimeout(resolve, 2000))

  // Create export directory
  const exportDir = path.join(process.cwd(), 'public', 'exports', projectId)
  if (!fs.existsSync(exportDir)) {
    fs.mkdirSync(exportDir, { recursive: true })
  }

  // Create mock export files with plan-specific content
  const watermarkText = userPlan === 'free' ? '\n\n[WATERMARK — FREE EXPORT]' : ''

  const mockPdf = `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
>>
endobj

4 0 obj
<<
/Length ${44 + watermarkText.length}
>>
stream
BT
/F1 12 Tf
72 720 Td
(${projectId} - Formatted Book${watermarkText}) Tj
ET
endstream
endobj

xref
0 5
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000189 00000 n
trailer
<<
/Size 5
/Root 1 0 R
>>
startxref
${285 + watermarkText.length}
%%EOF`

  const mockEpub = `EPUB File for ${projectId}

This is a sample EPUB file generated by BookMagic using the ${templateId} template.
In a production environment, this would be a proper EPUB file created by Pandoc.

User Plan: ${userPlan.toUpperCase()}
${userPlan === 'free' ? 'Note: PDF version includes watermark for free plan users.' : 'Premium export - no watermarks!'}

Content Preview:
${projectId.charAt(0).toUpperCase() + projectId.slice(1)} - Sample Manuscript

This is a professionally formatted manuscript for project ${projectId}.

Chapter One: The Beginning
Lorem ipsum dolor sit amet, consectetur adipiscing elit...

Generated by BookMagic - Professional Book Formatting`

  const mockLicense = `Font License Agreement

This package includes fonts that are licensed for use in published books.

Included Fonts:
- EB Garamond (Open Font License)
- Lora (Open Font License)
- Source Serif Pro (Open Font License)

These fonts are free to use for both personal and commercial projects.
For more information, visit the respective font foundries.

Generated by BookMagic - Professional Book Formatting
User Plan: ${userPlan.toUpperCase()}`

  const mockChecklist = `KDP Publishing Checklist for ${projectId}

✓ Manuscript formatted with professional template (${templateId})
✓ Proper page margins and spacing
✓ Consistent typography throughout
✓ Table of contents generated
✓ Print-ready PDF created${userPlan === 'free' ? ' (includes watermark - upgrade to Pro for clean PDFs)' : ' (clean, professional PDF)'}
✓ EPUB file validated
✓ Font licenses included
✓ Ready for upload to KDP

User Plan: ${userPlan.toUpperCase()}
${userPlan === 'free' ? 'Upgrade to Pro for watermark-free exports and unlimited projects!' : 'Thank you for being a Pro user!'}

Generated by BookMagic
Visit https://kdp.amazon.com for publishing guidelines`

  // Write individual files
  fs.writeFileSync(path.join(exportDir, `${projectId}.pdf`), mockPdf)
  fs.writeFileSync(path.join(exportDir, `${projectId}.epub`), mockEpub)
  fs.writeFileSync(path.join(exportDir, 'LICENSE.txt'), mockLicense)
  fs.writeFileSync(path.join(exportDir, 'KDP_Checklist.txt'), mockChecklist)

  // Create a simple ZIP-like file (for demo purposes, just concatenate files)
  const zipContent = `BookMagic Export Package for ${projectId}
Template: ${templateId}
User Plan: ${userPlan.toUpperCase()}
Generated: ${new Date().toISOString()}

This package contains:
- ${projectId}.pdf (Print-ready PDF${userPlan === 'free' ? ' - includes watermark' : ' - clean, professional'})
- ${projectId}.epub (Digital book format)
- LICENSE.txt (Font licenses)
- KDP_Checklist.txt (Publishing guidelines)

${userPlan === 'free'
    ? 'Free Plan: PDFs include watermarks. Upgrade to Pro for clean exports!'
    : 'Pro Plan: Clean, professional exports with no watermarks.'
  }

Files are ready for publishing on Amazon KDP, IngramSpark, and other platforms.

Generated by BookMagic - Professional Book Formatting
`

  fs.writeFileSync(path.join(exportDir, 'export.zip'), zipContent)
}

// Real worker conversion using the Node.js worker
async function realWorkerConvert(projectId: string, templateId: string, userPlan: string = 'free'): Promise<{ success: boolean; stdout?: string; stderr?: string; error?: string }> {
  return new Promise((resolve) => {
    console.log(`Starting real worker conversion for project ${projectId}`)

    // Check if uploaded file exists
    const uploadedFilePath = getUploadedFilePath(projectId)
    if (uploadedFilePath) {
      console.log(`Found uploaded file for ${projectId}: ${uploadedFilePath}`)
    } else {
      console.log(`No uploaded file found for ${projectId}, worker will use sample content`)
    }

    // Construct worker path dynamically to avoid Next.js module resolution issues
    const converterDir = path.join(process.cwd(), 'converter')
    const workerFileName = ['worker', 'js'].join('.')
    const workerPath = path.join(converterDir, workerFileName)

    // Check if worker exists
    if (!fs.existsSync(workerPath)) {
      console.error(`Worker not found at: ${workerPath}`)
      resolve({
        success: false,
        error: `Worker script not found at ${workerPath}`
      })
      return
    }

    console.log(`Spawning worker: node ${workerFileName} ${projectId} ${templateId} ${userPlan}`)

    const worker = spawn('node', [workerFileName, projectId, templateId, userPlan], {
      cwd: converterDir,
      stdio: ['pipe', 'pipe', 'pipe']
    })

    let stdout = ''
    let stderr = ''

    worker.stdout.on('data', (data) => {
      const output = data.toString()
      stdout += output
      console.log(`Worker stdout: ${output.trim()}`)
    })

    worker.stderr.on('data', (data) => {
      const output = data.toString()
      stderr += output
      console.error(`Worker stderr: ${output.trim()}`)
    })

    worker.on('close', (code) => {
      console.log(`Worker process exited with code ${code}`)

      if (code === 0) {
        resolve({
          success: true,
          stdout: stdout.trim(),
          stderr: stderr.trim()
        })
      } else {
        resolve({
          success: false,
          stdout: stdout.trim(),
          stderr: stderr.trim(),
          error: `Worker process exited with code ${code}`
        })
      }
    })

    worker.on('error', (error) => {
      console.error(`Worker process error: ${error.message}`)
      resolve({
        success: false,
        error: `Worker process error: ${error.message}`,
        stderr: stderr.trim()
      })
    })

    // Set a timeout to prevent hanging
    setTimeout(() => {
      if (!worker.killed) {
        console.log('Worker timeout, killing process')
        worker.kill()
        resolve({
          success: false,
          error: 'Worker process timeout',
          stdout: stdout.trim(),
          stderr: stderr.trim()
        })
      }
    }, 60000) // 60 second timeout
  })
}

export async function POST(request: NextRequest) {
  try {
    const { projectId, templateId, userPlan = 'free' } = await request.json()

    if (!projectId || !templateId) {
      return NextResponse.json(
        { error: 'Missing projectId or templateId' },
        { status: 400 }
      )
    }

    console.log(`Starting export for project ${projectId} with template ${templateId} (${userPlan} plan)`)

    try {
      let result

      if (USE_REAL_WORKER) {
        console.log('Using real worker for conversion')
        result = await realWorkerConvert(projectId, templateId, userPlan)
      } else {
        console.log('Using mock converter for conversion')
        await mockConvert(projectId, templateId, userPlan)
        result = { success: true, stdout: 'Mock conversion completed' }
      }

      if (!result.success) {
        return NextResponse.json({
          success: false,
          error: result.error || 'Conversion failed',
          stdout: result.stdout,
          stderr: result.stderr
        }, { status: 500 })
      }

      // Check if export file was created
      const exportPath = path.join(process.cwd(), 'public', 'exports', projectId, 'export.zip')

      if (fs.existsSync(exportPath)) {
        const stats = fs.statSync(exportPath)
        console.log(`Export file created successfully: ${exportPath} (${stats.size} bytes)`)

        return NextResponse.json({
          success: true,
          message: 'Export completed successfully',
          projectId,
          templateId,
          userPlan,
          exportPath: `/exports/${projectId}/export.zip`,
          stdout: result.stdout || `Export completed for project ${projectId} using ${templateId} template (${userPlan} plan)${userPlan === 'free' ? ' - PDF includes watermark' : ' - clean PDF'}`
        })
      } else {
        return NextResponse.json({
          success: false,
          error: 'Export file was not created',
          projectId,
          templateId,
          stdout: result.stdout,
          stderr: result.stderr
        }, { status: 500 })
      }

    } catch (conversionError) {
      console.error('Conversion error:', conversionError)
      return NextResponse.json({
        success: false,
        error: 'Conversion process failed',
        details: conversionError instanceof Error ? conversionError.message : 'Unknown conversion error'
      }, { status: 500 })
    }

  } catch (error) {
    console.error('Export API error:', error)
    return NextResponse.json(
      {
        success: false,
        error: 'Internal server error',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const projectId = searchParams.get('projectId')

  if (!projectId) {
    return NextResponse.json(
      { error: 'Missing projectId parameter' },
      { status: 400 }
    )
  }

  // Check export status
  const exportPath = path.join(process.cwd(), 'public', 'exports', projectId, 'export.zip')
  const exportExists = fs.existsSync(exportPath)

  if (exportExists) {
    const stats = fs.statSync(exportPath)
    return NextResponse.json({
      ready: true,
      projectId,
      exportPath: `/exports/${projectId}/export.zip`,
      size: stats.size,
      createdAt: stats.birthtime
    })
  } else {
    return NextResponse.json({
      ready: false,
      projectId
    })
  }
} 